// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkkXfbWjwuDhAgv9HRQcepVX-EacnQXZQ',
    appId: '1:110430873871:web:7f96027ffa8520edc6367a',
    messagingSenderId: '110430873871',
    projectId: 'fatiel',
    authDomain: 'fatiel.firebaseapp.com',
    storageBucket: 'fatiel.firebasestorage.app',
    measurementId: 'G-36NJK6R6ED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHs1ZBUYp3u5QqI3J1Q1qEVXvZn5JE3Ac',
    appId: '1:110430873871:android:43727ba57d3b045ac6367a',
    messagingSenderId: '110430873871',
    projectId: 'fatiel',
    storageBucket: 'fatiel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuyCj5_OM25NYi6IQbl-aq8skQ6uLHuck',
    appId: '1:110430873871:ios:c0d6a984560ca535c6367a',
    messagingSenderId: '110430873871',
    projectId: 'fatiel',
    storageBucket: 'fatiel.firebasestorage.app',
    iosBundleId: 'com.example.hotelBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuyCj5_OM25NYi6IQbl-aq8skQ6uLHuck',
    appId: '1:110430873871:ios:c0d6a984560ca535c6367a',
    messagingSenderId: '110430873871',
    projectId: 'fatiel',
    storageBucket: 'fatiel.firebasestorage.app',
    iosBundleId: 'com.example.hotelBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkkXfbWjwuDhAgv9HRQcepVX-EacnQXZQ',
    appId: '1:110430873871:web:e23bec86abc0138dc6367a',
    messagingSenderId: '110430873871',
    projectId: 'fatiel',
    authDomain: 'fatiel.firebaseapp.com',
    storageBucket: 'fatiel.firebasestorage.app',
    measurementId: 'G-GP2GFJE0ZM',
  );
}
