name: fatiel
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  cloud_firestore: ^4.14.0
  carousel_slider: ^4.2.1 
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.8.0
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  cached_network_image: 3.3.0
  intl: ^0.19.0
  provider: ^6.1.2
  rxdart: ^0.27.7
  url_launcher: ^6.2.4
  flutter_staggered_animations: ^1.1.1
  image_picker: ^1.0.8
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  flutter_paginate: ^1.0.0
  smooth_page_indicator: ^1.2.1
  iconsax: ^0.0.8
  liquid_progress_indicator: ^0.4.0
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icons/splash_screen.svg"
  adaptive_icon_background: "#F3E5F5" # Using ThemeColors.background
  adaptive_icon_foreground: "assets/icons/splash_screen.svg"
  min_sdk_android: 21 # Required for adaptive icons

flutter:
  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-Thin.ttf
          weight: 100
        - asset: assets/fonts/Barlow-Light.ttf
          weight: 300
        - asset: assets/fonts/Barlow-Regular.ttf
          weight: 400
        - asset: assets/fonts/Barlow-Medium.ttf
          weight: 500
        - asset: assets/fonts/Barlow-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Barlow-Bold.ttf
          weight: 700
        - asset: assets/fonts/Barlow-Black.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900

  assets:
    - assets/icons/splash_screen.svg
    - assets/images/
    - assets/wilayas/
    - .env
  uses-material-design: true